# Generated by Django 5.0.6 on 2024-06-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teach_maths", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="answers",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="questions",
            new_name="question",
        ),
    ]
